/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as ProcessosRouteImport } from './routes/processos'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as ConsultasRouteImport } from './routes/consultas'
import { Route as CertificadosRouteImport } from './routes/certificados'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as BaseInformacoesEmpresasRouteImport } from './routes/base-informacoes-empresas'
import { Route as BaseEmpresasRouteImport } from './routes/base-empresas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TarefaSlugRouteImport } from './routes/tarefa.$slug'
import { Route as ProcessoValidacaoCadastroRouteImport } from './routes/processo.validacao-cadastro'
import { Route as ProcessoSittaxSnRouteImport } from './routes/processo.sittax-sn'
import { Route as ProcessoSittaxMonitoraRouteImport } from './routes/processo.sittax-monitora'
import { Route as ProcessoSaamRouteImport } from './routes/processo.saam'
import { Route as ProcessoProcuracoesRouteImport } from './routes/processo.procuracoes'
import { Route as ProcessoPdcaMonitoramentoRouteImport } from './routes/processo.pdca-monitoramento'
import { Route as ProcessoObrigacoesAcessoriasRouteImport } from './routes/processo.obrigacoes-acessorias'
import { Route as ProcessoIrpjCsllLpRouteImport } from './routes/processo.irpj-csll-lp'
import { Route as ProcessoIrpjCsllRouteImport } from './routes/processo.irpj-csll'
import { Route as ProcessoGestaoObrigacoesRouteImport } from './routes/processo.gestao-obrigacoes'
import { Route as ProcessoFiscalEstadosRouteImport } from './routes/processo.fiscal-estados'
import { Route as ProcessoEntregasContabilRouteImport } from './routes/processo.entregas-contabil'
import { Route as ProcessoControleTagsRouteImport } from './routes/processo.controle-tags'
import { Route as ProcessoComposicaoContabilRouteImport } from './routes/processo.composicao-contabil'
import { Route as ProcessoAuditoriaCadastralRouteImport } from './routes/processo.auditoria-cadastral'
import { Route as ProcessoSlugRouteImport } from './routes/processo.$slug'
import { Route as ConsultaMatrizRaciRouteImport } from './routes/consulta.matriz-raci'
import { Route as ConsultaEmpresasRouteImport } from './routes/consulta.empresas'
import { Route as ConsultaDonosTagsRouteImport } from './routes/consulta.donos-tags'
import { Route as ConsultaSlugRouteImport } from './routes/consulta.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicOkrSyncRouteImport } from './routes/api/public/okr-sync'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosRoute = ProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultasRoute = ConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadosRoute = CertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseInformacoesEmpresasRoute = BaseInformacoesEmpresasRouteImport.update({
  id: '/base-informacoes-empresas',
  path: '/base-informacoes-empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseEmpresasRoute = BaseEmpresasRouteImport.update({
  id: '/base-empresas',
  path: '/base-empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefaSlugRoute = TarefaSlugRouteImport.update({
  id: '/tarefa/$slug',
  path: '/tarefa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoValidacaoCadastroRoute =
  ProcessoValidacaoCadastroRouteImport.update({
    id: '/processo/validacao-cadastro',
    path: '/processo/validacao-cadastro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcessoSittaxSnRoute = ProcessoSittaxSnRouteImport.update({
  id: '/processo/sittax-sn',
  path: '/processo/sittax-sn',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoSittaxMonitoraRoute = ProcessoSittaxMonitoraRouteImport.update({
  id: '/processo/sittax-monitora',
  path: '/processo/sittax-monitora',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoSaamRoute = ProcessoSaamRouteImport.update({
  id: '/processo/saam',
  path: '/processo/saam',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoProcuracoesRoute = ProcessoProcuracoesRouteImport.update({
  id: '/processo/procuracoes',
  path: '/processo/procuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoPdcaMonitoramentoRoute =
  ProcessoPdcaMonitoramentoRouteImport.update({
    id: '/processo/pdca-monitoramento',
    path: '/processo/pdca-monitoramento',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcessoObrigacoesAcessoriasRoute =
  ProcessoObrigacoesAcessoriasRouteImport.update({
    id: '/processo/obrigacoes-acessorias',
    path: '/processo/obrigacoes-acessorias',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcessoIrpjCsllLpRoute = ProcessoIrpjCsllLpRouteImport.update({
  id: '/processo/irpj-csll-lp',
  path: '/processo/irpj-csll-lp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoIrpjCsllRoute = ProcessoIrpjCsllRouteImport.update({
  id: '/processo/irpj-csll',
  path: '/processo/irpj-csll',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoGestaoObrigacoesRoute =
  ProcessoGestaoObrigacoesRouteImport.update({
    id: '/processo/gestao-obrigacoes',
    path: '/processo/gestao-obrigacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcessoFiscalEstadosRoute = ProcessoFiscalEstadosRouteImport.update({
  id: '/processo/fiscal-estados',
  path: '/processo/fiscal-estados',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoEntregasContabilRoute =
  ProcessoEntregasContabilRouteImport.update({
    id: '/processo/entregas-contabil',
    path: '/processo/entregas-contabil',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcessoControleTagsRoute = ProcessoControleTagsRouteImport.update({
  id: '/processo/controle-tags',
  path: '/processo/controle-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoComposicaoContabilRoute =
  ProcessoComposicaoContabilRouteImport.update({
    id: '/processo/composicao-contabil',
    path: '/processo/composicao-contabil',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcessoAuditoriaCadastralRoute =
  ProcessoAuditoriaCadastralRouteImport.update({
    id: '/processo/auditoria-cadastral',
    path: '/processo/auditoria-cadastral',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcessoSlugRoute = ProcessoSlugRouteImport.update({
  id: '/processo/$slug',
  path: '/processo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaMatrizRaciRoute = ConsultaMatrizRaciRouteImport.update({
  id: '/consulta/matriz-raci',
  path: '/consulta/matriz-raci',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaEmpresasRoute = ConsultaEmpresasRouteImport.update({
  id: '/consulta/empresas',
  path: '/consulta/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaDonosTagsRoute = ConsultaDonosTagsRouteImport.update({
  id: '/consulta/donos-tags',
  path: '/consulta/donos-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaSlugRoute = ConsultaSlugRouteImport.update({
  id: '/consulta/$slug',
  path: '/consulta/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOkrSyncRoute = ApiPublicOkrSyncRouteImport.update({
  id: '/api/public/okr-sync',
  path: '/api/public/okr-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/base-empresas': typeof BaseEmpresasRoute
  '/base-informacoes-empresas': typeof BaseInformacoesEmpresasRoute
  '/carteira': typeof CarteiraRoute
  '/certificados': typeof CertificadosRoute
  '/consultas': typeof ConsultasRoute
  '/dados': typeof DadosRoute
  '/mcp': typeof McpRoute
  '/performance': typeof PerformanceRoute
  '/processos': typeof ProcessosRoute
  '/tarefas': typeof TarefasRoute
  '/usuarios': typeof UsuariosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/consulta/$slug': typeof ConsultaSlugRoute
  '/consulta/donos-tags': typeof ConsultaDonosTagsRoute
  '/consulta/empresas': typeof ConsultaEmpresasRoute
  '/consulta/matriz-raci': typeof ConsultaMatrizRaciRoute
  '/processo/$slug': typeof ProcessoSlugRoute
  '/processo/auditoria-cadastral': typeof ProcessoAuditoriaCadastralRoute
  '/processo/composicao-contabil': typeof ProcessoComposicaoContabilRoute
  '/processo/controle-tags': typeof ProcessoControleTagsRoute
  '/processo/entregas-contabil': typeof ProcessoEntregasContabilRoute
  '/processo/fiscal-estados': typeof ProcessoFiscalEstadosRoute
  '/processo/gestao-obrigacoes': typeof ProcessoGestaoObrigacoesRoute
  '/processo/irpj-csll': typeof ProcessoIrpjCsllRoute
  '/processo/irpj-csll-lp': typeof ProcessoIrpjCsllLpRoute
  '/processo/obrigacoes-acessorias': typeof ProcessoObrigacoesAcessoriasRoute
  '/processo/pdca-monitoramento': typeof ProcessoPdcaMonitoramentoRoute
  '/processo/procuracoes': typeof ProcessoProcuracoesRoute
  '/processo/saam': typeof ProcessoSaamRoute
  '/processo/sittax-monitora': typeof ProcessoSittaxMonitoraRoute
  '/processo/sittax-sn': typeof ProcessoSittaxSnRoute
  '/processo/validacao-cadastro': typeof ProcessoValidacaoCadastroRoute
  '/tarefa/$slug': typeof TarefaSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/okr-sync': typeof ApiPublicOkrSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/base-empresas': typeof BaseEmpresasRoute
  '/base-informacoes-empresas': typeof BaseInformacoesEmpresasRoute
  '/carteira': typeof CarteiraRoute
  '/certificados': typeof CertificadosRoute
  '/consultas': typeof ConsultasRoute
  '/dados': typeof DadosRoute
  '/mcp': typeof McpRoute
  '/performance': typeof PerformanceRoute
  '/processos': typeof ProcessosRoute
  '/tarefas': typeof TarefasRoute
  '/usuarios': typeof UsuariosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/consulta/$slug': typeof ConsultaSlugRoute
  '/consulta/donos-tags': typeof ConsultaDonosTagsRoute
  '/consulta/empresas': typeof ConsultaEmpresasRoute
  '/consulta/matriz-raci': typeof ConsultaMatrizRaciRoute
  '/processo/$slug': typeof ProcessoSlugRoute
  '/processo/auditoria-cadastral': typeof ProcessoAuditoriaCadastralRoute
  '/processo/composicao-contabil': typeof ProcessoComposicaoContabilRoute
  '/processo/controle-tags': typeof ProcessoControleTagsRoute
  '/processo/entregas-contabil': typeof ProcessoEntregasContabilRoute
  '/processo/fiscal-estados': typeof ProcessoFiscalEstadosRoute
  '/processo/gestao-obrigacoes': typeof ProcessoGestaoObrigacoesRoute
  '/processo/irpj-csll': typeof ProcessoIrpjCsllRoute
  '/processo/irpj-csll-lp': typeof ProcessoIrpjCsllLpRoute
  '/processo/obrigacoes-acessorias': typeof ProcessoObrigacoesAcessoriasRoute
  '/processo/pdca-monitoramento': typeof ProcessoPdcaMonitoramentoRoute
  '/processo/procuracoes': typeof ProcessoProcuracoesRoute
  '/processo/saam': typeof ProcessoSaamRoute
  '/processo/sittax-monitora': typeof ProcessoSittaxMonitoraRoute
  '/processo/sittax-sn': typeof ProcessoSittaxSnRoute
  '/processo/validacao-cadastro': typeof ProcessoValidacaoCadastroRoute
  '/tarefa/$slug': typeof TarefaSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/okr-sync': typeof ApiPublicOkrSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/base-empresas': typeof BaseEmpresasRoute
  '/base-informacoes-empresas': typeof BaseInformacoesEmpresasRoute
  '/carteira': typeof CarteiraRoute
  '/certificados': typeof CertificadosRoute
  '/consultas': typeof ConsultasRoute
  '/dados': typeof DadosRoute
  '/mcp': typeof McpRoute
  '/performance': typeof PerformanceRoute
  '/processos': typeof ProcessosRoute
  '/tarefas': typeof TarefasRoute
  '/usuarios': typeof UsuariosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/consulta/$slug': typeof ConsultaSlugRoute
  '/consulta/donos-tags': typeof ConsultaDonosTagsRoute
  '/consulta/empresas': typeof ConsultaEmpresasRoute
  '/consulta/matriz-raci': typeof ConsultaMatrizRaciRoute
  '/processo/$slug': typeof ProcessoSlugRoute
  '/processo/auditoria-cadastral': typeof ProcessoAuditoriaCadastralRoute
  '/processo/composicao-contabil': typeof ProcessoComposicaoContabilRoute
  '/processo/controle-tags': typeof ProcessoControleTagsRoute
  '/processo/entregas-contabil': typeof ProcessoEntregasContabilRoute
  '/processo/fiscal-estados': typeof ProcessoFiscalEstadosRoute
  '/processo/gestao-obrigacoes': typeof ProcessoGestaoObrigacoesRoute
  '/processo/irpj-csll': typeof ProcessoIrpjCsllRoute
  '/processo/irpj-csll-lp': typeof ProcessoIrpjCsllLpRoute
  '/processo/obrigacoes-acessorias': typeof ProcessoObrigacoesAcessoriasRoute
  '/processo/pdca-monitoramento': typeof ProcessoPdcaMonitoramentoRoute
  '/processo/procuracoes': typeof ProcessoProcuracoesRoute
  '/processo/saam': typeof ProcessoSaamRoute
  '/processo/sittax-monitora': typeof ProcessoSittaxMonitoraRoute
  '/processo/sittax-sn': typeof ProcessoSittaxSnRoute
  '/processo/validacao-cadastro': typeof ProcessoValidacaoCadastroRoute
  '/tarefa/$slug': typeof TarefaSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/okr-sync': typeof ApiPublicOkrSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/base-empresas'
    | '/base-informacoes-empresas'
    | '/carteira'
    | '/certificados'
    | '/consultas'
    | '/dados'
    | '/mcp'
    | '/performance'
    | '/processos'
    | '/tarefas'
    | '/usuarios'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/consulta/$slug'
    | '/consulta/donos-tags'
    | '/consulta/empresas'
    | '/consulta/matriz-raci'
    | '/processo/$slug'
    | '/processo/auditoria-cadastral'
    | '/processo/composicao-contabil'
    | '/processo/controle-tags'
    | '/processo/entregas-contabil'
    | '/processo/fiscal-estados'
    | '/processo/gestao-obrigacoes'
    | '/processo/irpj-csll'
    | '/processo/irpj-csll-lp'
    | '/processo/obrigacoes-acessorias'
    | '/processo/pdca-monitoramento'
    | '/processo/procuracoes'
    | '/processo/saam'
    | '/processo/sittax-monitora'
    | '/processo/sittax-sn'
    | '/processo/validacao-cadastro'
    | '/tarefa/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/okr-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/base-empresas'
    | '/base-informacoes-empresas'
    | '/carteira'
    | '/certificados'
    | '/consultas'
    | '/dados'
    | '/mcp'
    | '/performance'
    | '/processos'
    | '/tarefas'
    | '/usuarios'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/consulta/$slug'
    | '/consulta/donos-tags'
    | '/consulta/empresas'
    | '/consulta/matriz-raci'
    | '/processo/$slug'
    | '/processo/auditoria-cadastral'
    | '/processo/composicao-contabil'
    | '/processo/controle-tags'
    | '/processo/entregas-contabil'
    | '/processo/fiscal-estados'
    | '/processo/gestao-obrigacoes'
    | '/processo/irpj-csll'
    | '/processo/irpj-csll-lp'
    | '/processo/obrigacoes-acessorias'
    | '/processo/pdca-monitoramento'
    | '/processo/procuracoes'
    | '/processo/saam'
    | '/processo/sittax-monitora'
    | '/processo/sittax-sn'
    | '/processo/validacao-cadastro'
    | '/tarefa/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/okr-sync'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/base-empresas'
    | '/base-informacoes-empresas'
    | '/carteira'
    | '/certificados'
    | '/consultas'
    | '/dados'
    | '/mcp'
    | '/performance'
    | '/processos'
    | '/tarefas'
    | '/usuarios'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/consulta/$slug'
    | '/consulta/donos-tags'
    | '/consulta/empresas'
    | '/consulta/matriz-raci'
    | '/processo/$slug'
    | '/processo/auditoria-cadastral'
    | '/processo/composicao-contabil'
    | '/processo/controle-tags'
    | '/processo/entregas-contabil'
    | '/processo/fiscal-estados'
    | '/processo/gestao-obrigacoes'
    | '/processo/irpj-csll'
    | '/processo/irpj-csll-lp'
    | '/processo/obrigacoes-acessorias'
    | '/processo/pdca-monitoramento'
    | '/processo/procuracoes'
    | '/processo/saam'
    | '/processo/sittax-monitora'
    | '/processo/sittax-sn'
    | '/processo/validacao-cadastro'
    | '/tarefa/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/okr-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BaseEmpresasRoute: typeof BaseEmpresasRoute
  BaseInformacoesEmpresasRoute: typeof BaseInformacoesEmpresasRoute
  CarteiraRoute: typeof CarteiraRoute
  CertificadosRoute: typeof CertificadosRoute
  ConsultasRoute: typeof ConsultasRoute
  DadosRoute: typeof DadosRoute
  McpRoute: typeof McpRoute
  PerformanceRoute: typeof PerformanceRoute
  ProcessosRoute: typeof ProcessosRoute
  TarefasRoute: typeof TarefasRoute
  UsuariosRoute: typeof UsuariosRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ConsultaSlugRoute: typeof ConsultaSlugRoute
  ConsultaDonosTagsRoute: typeof ConsultaDonosTagsRoute
  ConsultaEmpresasRoute: typeof ConsultaEmpresasRoute
  ConsultaMatrizRaciRoute: typeof ConsultaMatrizRaciRoute
  ProcessoSlugRoute: typeof ProcessoSlugRoute
  ProcessoAuditoriaCadastralRoute: typeof ProcessoAuditoriaCadastralRoute
  ProcessoComposicaoContabilRoute: typeof ProcessoComposicaoContabilRoute
  ProcessoControleTagsRoute: typeof ProcessoControleTagsRoute
  ProcessoEntregasContabilRoute: typeof ProcessoEntregasContabilRoute
  ProcessoFiscalEstadosRoute: typeof ProcessoFiscalEstadosRoute
  ProcessoGestaoObrigacoesRoute: typeof ProcessoGestaoObrigacoesRoute
  ProcessoIrpjCsllRoute: typeof ProcessoIrpjCsllRoute
  ProcessoIrpjCsllLpRoute: typeof ProcessoIrpjCsllLpRoute
  ProcessoObrigacoesAcessoriasRoute: typeof ProcessoObrigacoesAcessoriasRoute
  ProcessoPdcaMonitoramentoRoute: typeof ProcessoPdcaMonitoramentoRoute
  ProcessoProcuracoesRoute: typeof ProcessoProcuracoesRoute
  ProcessoSaamRoute: typeof ProcessoSaamRoute
  ProcessoSittaxMonitoraRoute: typeof ProcessoSittaxMonitoraRoute
  ProcessoSittaxSnRoute: typeof ProcessoSittaxSnRoute
  ProcessoValidacaoCadastroRoute: typeof ProcessoValidacaoCadastroRoute
  TarefaSlugRoute: typeof TarefaSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicOkrSyncRoute: typeof ApiPublicOkrSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos': {
      id: '/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultas': {
      id: '/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof ConsultasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificados': {
      id: '/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof CertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-informacoes-empresas': {
      id: '/base-informacoes-empresas'
      path: '/base-informacoes-empresas'
      fullPath: '/base-informacoes-empresas'
      preLoaderRoute: typeof BaseInformacoesEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-empresas': {
      id: '/base-empresas'
      path: '/base-empresas'
      fullPath: '/base-empresas'
      preLoaderRoute: typeof BaseEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefa/$slug': {
      id: '/tarefa/$slug'
      path: '/tarefa/$slug'
      fullPath: '/tarefa/$slug'
      preLoaderRoute: typeof TarefaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/validacao-cadastro': {
      id: '/processo/validacao-cadastro'
      path: '/processo/validacao-cadastro'
      fullPath: '/processo/validacao-cadastro'
      preLoaderRoute: typeof ProcessoValidacaoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/sittax-sn': {
      id: '/processo/sittax-sn'
      path: '/processo/sittax-sn'
      fullPath: '/processo/sittax-sn'
      preLoaderRoute: typeof ProcessoSittaxSnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/sittax-monitora': {
      id: '/processo/sittax-monitora'
      path: '/processo/sittax-monitora'
      fullPath: '/processo/sittax-monitora'
      preLoaderRoute: typeof ProcessoSittaxMonitoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/saam': {
      id: '/processo/saam'
      path: '/processo/saam'
      fullPath: '/processo/saam'
      preLoaderRoute: typeof ProcessoSaamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/procuracoes': {
      id: '/processo/procuracoes'
      path: '/processo/procuracoes'
      fullPath: '/processo/procuracoes'
      preLoaderRoute: typeof ProcessoProcuracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/pdca-monitoramento': {
      id: '/processo/pdca-monitoramento'
      path: '/processo/pdca-monitoramento'
      fullPath: '/processo/pdca-monitoramento'
      preLoaderRoute: typeof ProcessoPdcaMonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/obrigacoes-acessorias': {
      id: '/processo/obrigacoes-acessorias'
      path: '/processo/obrigacoes-acessorias'
      fullPath: '/processo/obrigacoes-acessorias'
      preLoaderRoute: typeof ProcessoObrigacoesAcessoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/irpj-csll-lp': {
      id: '/processo/irpj-csll-lp'
      path: '/processo/irpj-csll-lp'
      fullPath: '/processo/irpj-csll-lp'
      preLoaderRoute: typeof ProcessoIrpjCsllLpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/irpj-csll': {
      id: '/processo/irpj-csll'
      path: '/processo/irpj-csll'
      fullPath: '/processo/irpj-csll'
      preLoaderRoute: typeof ProcessoIrpjCsllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/gestao-obrigacoes': {
      id: '/processo/gestao-obrigacoes'
      path: '/processo/gestao-obrigacoes'
      fullPath: '/processo/gestao-obrigacoes'
      preLoaderRoute: typeof ProcessoGestaoObrigacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/fiscal-estados': {
      id: '/processo/fiscal-estados'
      path: '/processo/fiscal-estados'
      fullPath: '/processo/fiscal-estados'
      preLoaderRoute: typeof ProcessoFiscalEstadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/entregas-contabil': {
      id: '/processo/entregas-contabil'
      path: '/processo/entregas-contabil'
      fullPath: '/processo/entregas-contabil'
      preLoaderRoute: typeof ProcessoEntregasContabilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/controle-tags': {
      id: '/processo/controle-tags'
      path: '/processo/controle-tags'
      fullPath: '/processo/controle-tags'
      preLoaderRoute: typeof ProcessoControleTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/composicao-contabil': {
      id: '/processo/composicao-contabil'
      path: '/processo/composicao-contabil'
      fullPath: '/processo/composicao-contabil'
      preLoaderRoute: typeof ProcessoComposicaoContabilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/auditoria-cadastral': {
      id: '/processo/auditoria-cadastral'
      path: '/processo/auditoria-cadastral'
      fullPath: '/processo/auditoria-cadastral'
      preLoaderRoute: typeof ProcessoAuditoriaCadastralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo/$slug': {
      id: '/processo/$slug'
      path: '/processo/$slug'
      fullPath: '/processo/$slug'
      preLoaderRoute: typeof ProcessoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta/matriz-raci': {
      id: '/consulta/matriz-raci'
      path: '/consulta/matriz-raci'
      fullPath: '/consulta/matriz-raci'
      preLoaderRoute: typeof ConsultaMatrizRaciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta/empresas': {
      id: '/consulta/empresas'
      path: '/consulta/empresas'
      fullPath: '/consulta/empresas'
      preLoaderRoute: typeof ConsultaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta/donos-tags': {
      id: '/consulta/donos-tags'
      path: '/consulta/donos-tags'
      fullPath: '/consulta/donos-tags'
      preLoaderRoute: typeof ConsultaDonosTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta/$slug': {
      id: '/consulta/$slug'
      path: '/consulta/$slug'
      fullPath: '/consulta/$slug'
      preLoaderRoute: typeof ConsultaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/okr-sync': {
      id: '/api/public/okr-sync'
      path: '/api/public/okr-sync'
      fullPath: '/api/public/okr-sync'
      preLoaderRoute: typeof ApiPublicOkrSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BaseEmpresasRoute: BaseEmpresasRoute,
  BaseInformacoesEmpresasRoute: BaseInformacoesEmpresasRoute,
  CarteiraRoute: CarteiraRoute,
  CertificadosRoute: CertificadosRoute,
  ConsultasRoute: ConsultasRoute,
  DadosRoute: DadosRoute,
  McpRoute: McpRoute,
  PerformanceRoute: PerformanceRoute,
  ProcessosRoute: ProcessosRoute,
  TarefasRoute: TarefasRoute,
  UsuariosRoute: UsuariosRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ConsultaSlugRoute: ConsultaSlugRoute,
  ConsultaDonosTagsRoute: ConsultaDonosTagsRoute,
  ConsultaEmpresasRoute: ConsultaEmpresasRoute,
  ConsultaMatrizRaciRoute: ConsultaMatrizRaciRoute,
  ProcessoSlugRoute: ProcessoSlugRoute,
  ProcessoAuditoriaCadastralRoute: ProcessoAuditoriaCadastralRoute,
  ProcessoComposicaoContabilRoute: ProcessoComposicaoContabilRoute,
  ProcessoControleTagsRoute: ProcessoControleTagsRoute,
  ProcessoEntregasContabilRoute: ProcessoEntregasContabilRoute,
  ProcessoFiscalEstadosRoute: ProcessoFiscalEstadosRoute,
  ProcessoGestaoObrigacoesRoute: ProcessoGestaoObrigacoesRoute,
  ProcessoIrpjCsllRoute: ProcessoIrpjCsllRoute,
  ProcessoIrpjCsllLpRoute: ProcessoIrpjCsllLpRoute,
  ProcessoObrigacoesAcessoriasRoute: ProcessoObrigacoesAcessoriasRoute,
  ProcessoPdcaMonitoramentoRoute: ProcessoPdcaMonitoramentoRoute,
  ProcessoProcuracoesRoute: ProcessoProcuracoesRoute,
  ProcessoSaamRoute: ProcessoSaamRoute,
  ProcessoSittaxMonitoraRoute: ProcessoSittaxMonitoraRoute,
  ProcessoSittaxSnRoute: ProcessoSittaxSnRoute,
  ProcessoValidacaoCadastroRoute: ProcessoValidacaoCadastroRoute,
  TarefaSlugRoute: TarefaSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicOkrSyncRoute: ApiPublicOkrSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
